---
title: "InsightPresentation"
author: "George Williford"
date: "3/22/2020"
output: html_document
---

# Data wrangling
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

# Data wrangling
```{r datawrangling}
mcy <- icow_part_cyr %>% group_by(c) %>% summarize(
  mmid = mean(nmidiss, na.rm = T),
  matt = mean(attemptsp, na.rm = T), 
  magg = mean(agree, na.rm = T), 
  miss = mean(agreeiss, na.rm = T),
  scl = sum(one), 
  rat = mmid/matt,
  dif = mean(midissyr - attanyp, na.rm = T),
  
)
# mcy$matt <- ifelse(mcy$matt == 0, NA, mcy$matt)
# mcy$mmid <- ifelse(mcy$mmid == 0, NA, mcy$mmid)

# Number of Claims
```{r}
ggplot(aes(y = scl, x = c), data = mcy) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Number of Claims")
```

# Substantive agreements
```
ggplot(aes(y = miss, x = c), data = mcy) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Number of Substantive Agreements")
```{r}