---
title: "R Notebook"
output: html_notebook
---


```{r}
setwd("C:/Users/gwill/Dropbox/Research/Dissertation/Data Analysis")
library(dplyr)
library(ggplot2)
library(tvcure)
options(scipen = 999)
```

# Data wrangling
```{r datawrangling}
mcy <- icow_part_cyr %>% group_by(c) %>% summarize(
  mmid = mean(nmidiss, na.rm = T),
  matt = mean(attemptsp, na.rm = T), 
  magg = mean(agree, na.rm = T), 
  miss = mean(agreeiss, na.rm = T),
  scl = sum(one), 
  rat = mmid/matt,
  dif = mean(mmid - matt, na.rm = T)
)
summary(mcy)

icow_part_cyr$ddum = ifelse(icow_part_cyr$ldefense > 1, 1, 0)
```
# Number of Claims
```{r}
ggplot(aes(y = scl, x = c), data = mcy) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Number of Claims")
```

# Ratio of mids to agreements
```{r}
ggplot(aes(y = rat, x = c), data = mcy) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Number of Agreements") + ylim(0, 10)
```

# Average intensity (number of military conflicts minus settlement attempts)
```{r}
ggplot(aes(y = dif, x = c), data = mcy) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Dispute Intensity")
```

# Number of agreements
```{r}
ggplot(aes(y = magg, x = c), data = mcy[mcy$c < 100, ]) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Number of Agreements")
```

# Substantive agreements
```{r}
ggplot(aes(y = miss, x = c), data = mcy) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Mean of Substantive Agreements")
```
# Substantive agreements
```{r}
ggplot(aes(y = miss, x = c), data = mcy[mcy$c < 100, ]) + geom_point() + geom_smooth(method = "loess") + 
  xlab("Length of Dispute (in years)") + ylab("Mean of Substantive Agreements")
```
```{r}
ggplot(aes(y = matt, x = c), data = mcy) + geom_point(shape = 1, size = 2, color = "blue") +
  geom_smooth(method = "loess") + 
  geom_point(aes(y = mmid, x = c), color = "red", shape = 1, size = 2) + 
  geom_smooth(aes(y = mmid, x = c), method = "loess", color = "red") + 
  xlab("Length of Dispute (in years)") + ylab("Number of Peaceful Settlement Attempts") + 
  theme(panel.grid.major = element_line(colour = "grey"))
```

## 
```{r}
cl <- makeCluster(4, "SOCK"); registerDoSNOW(cl)
att <- tvcure(Surv(clstart, clstop, attanyp) ~ dee +
               icowsal + riveriss + mariss +
               recmidwt + recfatwt + recnowt + recyeswt +
               lag_pch_gdp_min,
             cureform =  ~ dee + aggtrademin + 
               demdy + autdy +
               lcaprat + ldefense + contdir + igosum, 
             data = icow_part_cyr, 
             var = T, nboot = 100, brglm = T); summary(att)
att_pred <- prediction3(att, "dee", c(-44, -29), type = "uncureprob", CI = T)
plot(att_pred)
stopCluster(cl)
```

```{r}
cl <- makeCluster(4, "SOCK"); registerDoSNOW(cl)
ag <- tvcure(Surv(clstart, clstop, agree) ~ dee +
                 icowsal + I(icowsal^2) + riveriss + mariss +
                 recmidwt + recfatwt + recnowt + recyeswt +
                 lag_pch_gdp_min,
               cureform =  ~ dee +
                 icowsal + I(icowsal^2) + riveriss + mariss +
                 demdy + autdy +
                 lcaprat + ddum + contdir + igosum, 
               data = icow_part_cyr, 
               var = T, nboot = 100, brglm = T); summary(ag)
stopCluster(cl)
```

```{r}
cl <- makeCluster(4, "SOCK"); registerDoSNOW(cl)
agiss <- tvcure(Surv(clstart, clstop, agreeiss) ~ dee + aggtrademin + 
                 recmidwt + recfatwt + recnowt + recyeswt +
                 lag_pch_gdp_min,
               cureform =  ~ dee + aggtrademin +
                 icowsal + I(icowsal^2) + riveriss + mariss +
                 samereg +
                 lcaprat + ldefense + contdir + igosum, 
               data = icow_part_cyr, 
               var = T, nboot = 100, brglm = T); summary(agiss)
stopCluster(cl)
agiss_pred <- prediction3(agiss, "dee", c(-46, -31), type = "uncureprob", CI = T)
plot(agiss_pred)
agiss_pred2 <- prediction3(agiss, "dee", c(-46, -31), type = "suncure", CI = T)
plot(agiss_pred2)
agiss_pred3 <- prediction3(agiss, "dee", c(-46, -31), type = "spop", CI = T)
plot(agiss_pred3)
```



```{r}
cl <- makeCluster(4, "SOCK"); registerDoSNOW(cl)
agiss2 <- tvcure(Surv(clstart, clstop, agreeiss) ~ dee + 
                  recmidwt + recfatwt + recnowt + recyeswt +
                  lag_pch_gdp_min,
                cureform =  ~ dee +
                                    recmidwt + recfatwt + recnowt + recyeswt +
                  icowsal + riveriss + mariss +
                  demdy + autdy +
                  lcaprat + ldefense + contdir + igosum, 
                data = icow_part_cyr, 
                var = T, nboot = 100, brglm = T); summary(agiss2)
stopCluster(cl)
agiss2_pred <- prediction3(agiss2, "frank", c(-44, -29), type = "uncureprob", CI = T)
plot(agiss2_pred, xlab = "Probability of Agreement", ylab = "Maximum Economic Interdependence (ln(Trade/GDP))")
```